# Generated by Django 2.1.4 on 2019-01-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='GroupMessage',
        ),
    ]
