# Generated by Django 2.1.4 on 2018-12-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181228_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='user',
            new_name='user_obj',
        ),
    ]
